server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://192.168.254.129:3306/student_score
    username: root
    password: 10909090
  devtools:
    livereload:
      port: 35555
  security:
    roles:
      admin: 'ADMIN'
      teacher: 'TEACHER'
      student: 'STUDENT'


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 设置jwt密钥
  secretKey: "JAWOIDJSABNKXJCHNZHDHWAIUDHJIOXZUCWKQNDIAYIIOHJZXCIYIUYAHJIXUZH"
  # 设置jwt过期时间 时间戳形式
  expireTime: 604800000
  #  设置jwt登录接口的uri
  loginUri: "/login"
  #  设置token请求头名称
  tokenHeaderName: "token"