spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://192.168.254.129:3306/student_score
    username: root
    password: 10909090
  devtools:
    livereload:
      port: 35555
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations: file:upload/
  jackson:
    time-zone: GMT+8

upload:
  path: upload/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 设置jwt密钥
  secretKey: "JAWOIDJSABNKXJCHNZHDHWAIUDHJIOXZUCWKQNDIAYIIOHJZXCIYIUYAHJIXUZH"
  # 设置jwt过期时间 时间戳形式
  expireTime: 604800000
  #  设置jwt登录接口的uri
  loginUri: "/login"
  #  设置token请求头名称
  tokenHeaderName: "token"
  #  在jwt filter中使用 使用startWith 做判断 注意带斜杠 否则 /banner***开头的都能访问
  allowPaths: /banner/