### 登录接口 所有用户通过这个接口登录
## 测试管理员账户登录
POST http://localhost:80/login
Content-Type: application/json

{
  "username": "8573924610",
  "password": "password"
}

###
## 测试老师账户登录
POST http://192.168.254.129:8080/login
Content-Type: application/json

{
  "username": "1012345678",
  "password": "password"
}

###
## 测试学生账户登录
POST http://192.168.254.129:8080/login
Content-Type: application/json

{
  "username": "1910010202",
  "password": "password"
}



### 成绩查询接口
## 管理员
GET http://localhost:80/score/2/1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ijg1NzM5MjQ2MTAiLCJleHAiOjE3MTQ3MTcwNDR9.myCP8jyX_LMcpr2waYZx7YZQChrBobPKbLQSpEdLKb8

###
##
GET http://localhost:80/score/10/1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjEwMTIzNDU2NzgiLCJleHAiOjE3MTQ3MTc2ODR9.y3IFO6Wtt4S7cKoXTn2l86Ix5n_PCT-49TE9hpX5ZfA

###
## 学生
GET http://localhost:80/score/10/1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjE5MTAwMTAyMDIiLCJleHAiOjE3MTQ3MTgxMzV9.4R35PlqldJ6drGGUpb_UGjDuiWC7ZRpw1h-0FG6QoL8

### 课程查询接口
## 学生
GET http://localhost:80/course/2/1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjE5MTAwMTAyMDIiLCJleHAiOjE3MTQ3MTgxMzV9.4R35PlqldJ6drGGUpb_UGjDuiWC7ZRpw1h-0FG6QoL8

### 其他接口
POST http://localhost:80/logout
Content-Type: application/json

###
GET http://localhost:80/student/info
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjE5MTAwMTAxMDEiLCJleHAiOjE3MTQ1ODAwMDN9.V4BECCfJecdcEjHhYidZdh0C5ZFPFMzB4SsB-nD5UGY

###
GET http://localhost:80/student/info
token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjEwMTIzNDU2NzgiLCJleHAiOjE3MTQ3MTc2ODR9.y3IFO6Wtt4S7cKoXTn2l86Ix5n_PCT-49TE9hpX5ZfA
